name: Build and Publish Docker Image to GitHub Packages

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAG: latest
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, Tag and push image to Container Registry
        run: |
          docker build --tag ${REGISTRY}/${{ github.repository }}:${IMAGE_TAG} .
          docker images
          docker push ${REGISTRY}/${{ github.repository }}:${IMAGE_TAG}
